name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag
        id: determine_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Generate release notes
        id: release_notes
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff.toml
          args: --latest --strip header

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.determine_tag.outputs.tag }}
          name: ${{ steps.determine_tag.outputs.tag }}
          body: ${{ steps.release_notes.outputs.content }}
          draft: false
          prerelease: ${{ contains(steps.determine_tag.outputs.tag, '-rc') || contains(steps.determine_tag.outputs.tag, '-beta') || contains(steps.determine_tag.outputs.tag, '-alpha') }}
          generate_release_notes: false

